-- 初始化数据库表结构
CREATE TABLE IF NOT EXISTS cart (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  image TEXT NOT NULL,
  price REAL NOT NULL,
  quantity INTEGER NOT NULL,
  stock INTEGER NOT NULL,
  tag TEXT
);

CREATE TABLE IF NOT EXISTS orders (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  orderNumber TEXT UNIQUE NOT NULL,
  date TEXT NOT NULL,
  status TEXT NOT NULL,
  totalAmount REAL NOT NULL
);

CREATE TABLE IF NOT EXISTS order_items (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  orderId INTEGER NOT NULL,
  productId TEXT NOT NULL,
  name TEXT NOT NULL,
  price REAL NOT NULL,
  quantity INTEGER NOT NULL,
  FOREIGN KEY (orderId) REFERENCES orders(id)
);

CREATE TABLE IF NOT EXISTS user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  isLoggedIn INTEGER NOT NULL DEFAULT 0
);